{
  "comments": [
    {
      "key": {
        "uuid": "e38d3b31_7c2913db",
        "filename": "extensions/openpower-pels/src.cpp",
        "patchSetId": 5
      },
      "lineNbr": 1400,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2021-08-27T13:09:34Z",
      "side": 1,
      "message": "I\u0027m worried the dbus calls when checking the dump status might throw an exception, and if you don\u0027t catch them here it would abort  creating the PEL.  So I think what you had before was fine, where you would just do:\n\ncatch (const std::exception\u0026 e)\n{\n}",
      "revId": "f3d7dc9720bde3332737ec943d8a668393a2e676",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "86da0ca3_d2e5004d",
        "filename": "extensions/openpower-pels/src.cpp",
        "patchSetId": 5
      },
      "lineNbr": 1400,
      "author": {
        "id": 1001062
      },
      "writtenOn": "2021-08-27T13:56:56Z",
      "side": 1,
      "message": "You mean dbus call itself can throw exception as-in my earlier patch I was throwing exception when subtree returned was empty?? \nDoes function checkDumpStatus() in latest patch looks fine (I have removed throwing exception)?",
      "parentUuid": "e38d3b31_7c2913db",
      "revId": "f3d7dc9720bde3332737ec943d8a668393a2e676",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}